/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppFriendsRouteImport } from './routes/_app/friends'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppSubjectsIndexRouteImport } from './routes/_app/subjects.index'
import { Route as AppSubjectsSubjectRouteImport } from './routes/_app/subjects.$subject'
import { Route as AppThreadsThreadIdRouteImport } from './routes/_app/threads.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSubjectsIndexRoute = AppSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsSubjectRoute = AppSubjectsSubjectRouteImport.update({
  id: '/subjects/$subject',
  path: '/subjects/$subject',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsThreadIdRoute = AppThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/friends': typeof AppFriendsRoute
  '/profile': typeof AppProfileRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/subjects/$subject': typeof AppSubjectsSubjectRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/subjects/': typeof AppSubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/friends': typeof AppFriendsRoute
  '/profile': typeof AppProfileRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/subjects/$subject': typeof AppSubjectsSubjectRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/subjects': typeof AppSubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/verify': typeof VerifyRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/friends': typeof AppFriendsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/subjects/$subject': typeof AppSubjectsSubjectRoute
  '/_app/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/_app/subjects/': typeof AppSubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset'
    | '/verify'
    | '/admin'
    | '/friends'
    | '/profile'
    | '/admin/users'
    | '/subjects/$subject'
    | '/threads/$threadId'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset'
    | '/verify'
    | '/admin'
    | '/friends'
    | '/profile'
    | '/admin/users'
    | '/subjects/$subject'
    | '/threads/$threadId'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset'
    | '/verify'
    | '/_app/admin'
    | '/_app/friends'
    | '/_app/profile'
    | '/_app/admin/users'
    | '/_app/subjects/$subject'
    | '/_app/threads/$threadId'
    | '/_app/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetRoute: typeof ResetRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/subjects/': {
      id: '/_app/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AppSubjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/$subject': {
      id: '/_app/subjects/$subject'
      path: '/subjects/$subject'
      fullPath: '/subjects/$subject'
      preLoaderRoute: typeof AppSubjectsSubjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/$threadId': {
      id: '/_app/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof AppThreadsThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppFriendsRoute: typeof AppFriendsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSubjectsSubjectRoute: typeof AppSubjectsSubjectRoute
  AppThreadsThreadIdRoute: typeof AppThreadsThreadIdRoute
  AppSubjectsIndexRoute: typeof AppSubjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppFriendsRoute: AppFriendsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSubjectsSubjectRoute: AppSubjectsSubjectRoute,
  AppThreadsThreadIdRoute: AppThreadsThreadIdRoute,
  AppSubjectsIndexRoute: AppSubjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetRoute: ResetRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
